# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6
# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db5e6ab3c3e8575c30f7800252f4aa1b9b3e719a96db690d76e169f733b1149b265bff2ce3e3288af798bb9b0ce76f4def4e34293f18e84c980d676aed650e3e
  frontend_url: "http://localhost:3000"
test:
  secret_key_base: 30ddad267ad0e89b94ab2b88bb36af9e34436d0ce159afb38b942f11f493769ac747026c5af5845a6ff6fe17264b5405a68af4a832e0fa520818e29016b4475e
  frontend_url: "http://localhost:3000"
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.
shared:
  bucket_name: "matchshirt"
  upload_host: "s3" # "digitalocean" or "s3"
  asset_host: "assets.applytodate.com"
  s3_asset_host: "d1f6wfmkq12kvb.cloudfront.net"
  mobile_base_uri: "applytodate://"

production:
  frontend_url: "https://applytodate.com"
